version: '2.1'

executors:
  java17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  release-build:
    executor: java17
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      - run: mvn --batch-mode release:prepare
      - run: mvn --batch-mode release:perform
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: /home/circleci/.m2/repository/com/tracqi/ME7Tuner/1.0

workflows:
  release-build-workflow:
    jobs:
      - release-build:
          filters:
            branches:
              only:
                - master

