version: '2.1'

executors:
  java17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  release-build:
    executor: java17
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      - run:
         command: |
          git config --global user.email "build@tracqi.com"
          git config --global user.name "Circle CI"
      - run: mvn --batch-mode release:prepare
      - run:
         command: |
          git checkout HEAD~1
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "export VERSION_NAME=$VERSION" >> "$BASH_ENV"
          source "$BASH_ENV"
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/archive-tmp
      - persist_to_workspace:
          root: target
          paths:
            - /archive-tmp

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
      - attach_workspace:
          at: target/archive-tmp
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION_NAME} ./home/circleci/project/target/archive-tmp/     
  

workflows:
  release-build-workflow:
    jobs:
      - release-build:
          filters:
            branches:
              only:
                - master
      - publish-github-release:
         requires:
            - release-build

