version: '2.1'
orbs:
  maven: circleci/maven@1.4.1

executors:
  java17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  release-build:
    executor: java17
    steps:
      - maven/test
      - store_artifacts:
          path: me7tuner/build/outputs/jar

workflows:
  maven_test:
    jobs:
      - release-build:
          filters:
            branches:
              only:
                - master

