version: '2.1'

executors:
  java17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  release-build:
    executor: java17
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: /home/circleci/project/target/

workflows:
  release-build-workflow:
    jobs:
      - release-build:
          filters:
            branches:
              only:
                - master

